lastfm-key = "208d7c4b02e046a0928eefd58f70325c"
lastfm-secret = "6b5e6fe6f5c874022c3291a8218a3a32"
enable-notifications = false
# min-play-time = 0
player-whitelist = ["ncspot"]
# filter-script = ""

# [[listenbrainz]]
# url = ""
# token = ""
